obscura/account/urls.py
from django.urls import path

from . import views


app_name = 'account'
urlpatterns = [
    path('register/', views.registerPage, name='register'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),
]

obscura/face/urls.py
from django.urls import path

from . import views


app_name = 'face'
urlpatterns = [
    # ex: /polls/
    path('', views.post_list, name='list'),
    path('create/', views.post_create, name='create'),
    path('<int:post_id>/', views.post_detail, name='detail'),
    path('<int:post_id>/edit/', views.post_update, name='update'),
    path('<int:post_id>/delete/', views.post_delete, name='delete'),
]

obscura/obscura/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path




urlpatterns = [
    path('admin/', admin.site.urls),
    path('face/', include('face.urls', namespace='face')),
    path('account/', include('account.urls', namespace='account')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

obscura/face/models.py
from django.db import models
from datetime import datetime

from django.urls import reverse
# Create your models here.


class Post(models.Model):
	title = models.CharField(max_length=120)
	image = models.FileField(null=True, blank=True)
	content = models.TextField(blank=True, null=True)
	updated = models.DateTimeField(auto_now=True, auto_now_add=False, blank=True)
	timestamp = models.DateTimeField(blank=True, default=datetime.now)

	def __unicode__(self):
		return self.title

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse("face:detail", args=[str(self.id)])
	

obscura/account/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm
from django import forms


class CreateUserForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2']

obscura/face/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = [
		    "title",
		    "content",
		    "image",
		]

obscura/account/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import loader

from django.contrib.auth.forms import UserCreationForm
from .forms import CreateUserForm
from django.contrib import messages


from django.contrib.auth import authenticate, login, logout
from .decorators import unauthenticated_user


# register view
@unauthenticated_user
def registerPage(request):
    form = CreateUserForm()
    context = { 
        "form": form 
    }
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(request, "Account was created for {}".format(user))
            return redirect('account:login')
    return render(request, 'account/register.html', context)


# login view
@unauthenticated_user
def loginPage(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('face:list')
        else:
            messages.info(request, 'Username OR password is incorrect')
            return redirect('account:login')
    context = {}
    return render(request, 'account/login.html', context)



def logoutUser(request):
    logout(request)
    return redirect('account:login')

obscura/face/views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404

from django.template import loader
from .forms import PostForm
from .models import Post

from django.contrib.auth.decorators import login_required


@login_required(login_url='account:login')
def post_create(request):
	form = PostForm(request.POST or None, request.FILES or None)

	if(form.is_valid()):
		instance = form.save(commit=False)
		instance.save()
		messages.success(request, "Successfully Created")
		return HttpResponseRedirect(instance.get_absolute_url())

	context = {
	    "form": form,
	}
	return render(request, "face/post_form.html", context)

@login_required(login_url='account:login')
def post_detail(request, post_id):
	instance = get_object_or_404(Post, id=post_id)
	context = {

	    "title": instance.title,
	    "instance": instance,
	}
	return render(request, "face/post_detail.html", context)

@login_required(login_url='account:login')
def post_list(request):
	queryset = Post.objects.all()
	context = {
		"object_list": queryset,
	    "title": "List"
	}
	return render(request, "face/base.html", context)

@login_required(login_url='account:login')
def post_update(request, post_id):
	instance = get_object_or_404(Post, id=post_id)
	form = PostForm(request.POST or None, request.FILES or None, instance=instance)
	if(form.is_valid()):
		instance = form.save(commit=False)
		instance.save()
		messages.success(request, "Item Saved")
		return HttpResponseRedirect(instance.get_absolute_url())
	context = {

	    "title": instance.title,
	    "instance": instance,
	    "form": form,
	}
	return render(request, "face/post_form.html", context)


@login_required(login_url='account:login')
def post_delete(request, post_id):
	instance = get_object_or_404(Post, id=post_id)
	instance.delete()
	messages.success(request, "Item Deleted")
	return redirect("face:list")

obscura/face/templates/face/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>{% block head_title %}Blog{% endblock head_title %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/css/bootstrap.min.css" integrity="sha384-VCmXjywReHh4PwowAiWNagnWcLhlEJLA5buUprzK8rxFgeH0kww/aWY76TfkUoSX" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}"/>
</head>
<body>
    {% if messages %}

    <div class="messages">

        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}


    <div class="container">
        <div class='col-sm-6 col-sm-offset-3'>
        <span>Hello, {{ request.user }}</span>
        <span><a href="{% url 'account:logout' %}">Logout</a></span>
        {% block content %}
            <h1>{{ title }}</h1>
            {% for obj in object_list %}
            <div class="row">
                <div class="col-sm-12">
                    <div class="card" >
                      {% if obj.image %}
                      <img src="{{ obj.image.url }}" class="card-img-top" alt="...">
                      {% endif %}
                      <div class="card-body">
                        <h5 class="card-title"><a href="{{ obj.get_absolute_url }}">{{ obj.title }}</a></h5><small>{{ obj.timestamp|timesince }}</small>
                        <p class="card-text">{{ obj.content|linebreaks|truncatechars:120 }}</p>
                        <a href="{{ obj.get_absolute_url }}" class="btn btn-primary">View</a>
                      </div>
                    </div>
                    <hr/>
                </div>
            </div>  
            {% endfor %}      
        {% endblock content %} 
    </div>
    </div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/js/bootstrap.min.js" integrity="sha384-XEerZL0cuoUbHE4nZReLT7nx9gQrQreJekYhJD9WNWhH8nEW+0c5qq7aIo2Wl30J" crossorigin="anonymous"></script>
</body>
</html>

obscura/face/templates/face/post_detail.html
{% extends "face/base.html" %}

{% block content %}


<div class='col-sm-6 col-sm-offset-3'>
    {% if instance.image %}
    <img src="{{ instance.image.url }}" class="img-fluid" />
    {% endif %}
    <h1>{{ title }}</h1>
    <small>{{ instance.timestamp }}</small><br/>
    {{ instance.content| linebreaks }}<br/>
</div>
{% endblock content %}s

obscura/face/templates/face/post_form.html
{% extends "face/base.html" %}

{% block content %}

<h1>Form</h1>
    <form method="POST" action='' enctype='multipart/form-data'>{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create Post"/>
    </form>

{% endblock content %}